# Generated by Django 4.0.1 on 2023-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель/Бренд')),
            ],
        ),
    ]
