# Generated by Django 4.0.1 on 2023-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0002_priceproduct_product_productlist_quantityproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_list',
        ),
    ]
