# Generated by Django 4.0.1 on 2023-01-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0003_remove_product_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='purchase_history.productlist', verbose_name='Список товаров'),
        ),
    ]
