# Generated by Django 4.0.1 on 2023-01-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0004_product_product_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand'], 'verbose_name': '01 Товар', 'verbose_name_plural': '01 Товары'},
        ),
    ]
