# Generated by Django 4.0.1 on 2023-02-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0006_remove_product_product_list_remove_productlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_list', to='purchase_history.Product', verbose_name='Товар'),
        ),
    ]
