# Generated by Django 4.0.1 on 2023-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0008_rename_product_productlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='products',
        ),
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_list', to='purchase_history.Product', verbose_name='Товары'),
        ),
    ]
