# Generated by Django 4.0.1 on 2023-02-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_history', '0009_remove_productlist_products_productlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость товара за 1 единицу/штуку'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='quantity_product',
            field=models.PositiveIntegerField(default=1, verbose_name='Количества товара'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='product',
        ),
        migrations.AddField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_list', to='purchase_history.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuantityProduct',
        ),
    ]
