# Generated by Django 4.0.1 on 2023-02-24 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_history', '0010_productlist_price_productlist_quantity_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название точки продаж')),
            ],
            options={
                'verbose_name': 'Точка продаж',
                'verbose_name_plural': 'Точки продаж',
            },
        ),
        migrations.CreateModel(
            name='ProductInPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Стоимость товара за 1 единицу/штуку')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Списки товаров',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата покупки')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма покупки без скидки')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма скидки')),
                ('total_cost_with_discount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма покупки со скидкой')),
                ('accumulated_bonuses', models.IntegerField(verbose_name='Накопленные бонусы')),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_history.pointofsale', verbose_name='Точка продаж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'История покупок',
            },
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Производитель/Бренд товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=1, max_length=255, verbose_name='Артикул товара'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PriceProduct',
        ),
        migrations.DeleteModel(
            name='ProductList',
        ),
        migrations.AddField(
            model_name='productinpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_history.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productinpurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_history.purchase', verbose_name='Покупка'),
        ),
    ]
