# Generated by Django 4.0.1 on 2023-01-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вид питомца')),
            ],
            options={
                'verbose_name': 'Вид питомца',
                'verbose_name_plural': '03 Вид питомца',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet', to='pet.pettype', verbose_name='Вид питомца')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pet', to=settings.AUTH_USER_MODEL, verbose_name='Владелец питомца')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': '02 Питомец',
            },
        ),
    ]
