# Generated by Django 4.0.1 on 2023-01-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': '01 Питомец'},
        ),
        migrations.AlterModelOptions(
            name='pettype',
            options={'verbose_name': 'Вид питомца', 'verbose_name_plural': '02 Вид питомца'},
        ),
    ]
