# Generated by Django 4.0.1 on 2022-12-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вид питомца')),
            ],
            options={
                'verbose_name': 'Вид питомца',
                'verbose_name_plural': '03 Вид питомца',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('pet_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pet', to='authentication.pettype', verbose_name='Вид питомца')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': '02 Питомец',
            },
        ),
    ]
