# Generated by Django 4.0.1 on 2022-12-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_pet_status',
            field=models.BooleanField(default=False, verbose_name='Статус добавления питомца'),
        ),
        migrations.AddField(
            model_name='user',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.pet', verbose_name='Питомцы'),
        ),
        migrations.AddField(
            model_name='user',
            name='reason_for_blocking',
            field=models.TextField(default=1, verbose_name='Причина блокировки'),
            preserve_default=False,
        ),
    ]
