# Generated by Django 4.0.1 on 2022-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_loyalty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_pet_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус добавления питомца'),
        ),
        migrations.AlterField(
            model_name='user',
            name='loyalty_level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Уровень лояльности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reason_for_blocking',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
    ]
