# Generated by Django 4.0.1 on 2022-12-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_blocked_alter_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
