# Generated by Django 4.0.1 on 2023-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fill',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
