# Generated by Django 4.0.1 on 2023-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_user_is_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_fill',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
