# Generated by Django 4.0.1 on 2023-01-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_pet_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
